### ISSUE TITLE
Метод containsGame(Game game) всегда выдает результат false 

### ISSUE THREAD

**Issue by alex311271** [alex311271/Team_diplom#1]
### Описание.
После внесения записи об игре в каталог метод containsGame(Game game) в классе GameStore не находит игру и возвращает результат false.

### Локализация дефекта.
https://github.com/alex311271/Team_diplom/blob/9edd425c2b17c915cd9b8994665a2f4b48dfb86c/src/main/java/ru/netology/GameStore.java#L32-L39

### Шаги воспроизведения.

1. Открыть [код программы/ветку gamestore](https://github.com/alex311271/Team_diplom.git) в IDEA
2. Запустить тест [shouldAddGame](https://github.com/alex311271/Team_diplom/blob/cd681cab1e0e183541e927cf910010b6d02e6f92/src/test/java/ru/netology/GameStoreTest.java#L11-L18) из класса [GameStoreTest](https://github.com/alex311271/Team_diplom/blob/cd681cab1e0e183541e927cf910010b6d02e6f92/src/test/java/ru/netology/GameStoreTest.java)
3. Проверить результат в консоли

**Ожидаемый результат:** тест проходит.
**Фактический результат:** тест не проходит. Сообщение в консоли: org.opentest4j.AssertionFailedError: Expected :3 Actual   :0 

### Скриншот

![shouldAddGame](https://user-images.githubusercontent.com/108461415/199968375-5eab749c-eb37-4bd6-aab2-00559ce0c159.png)

### Окружение

- **Операционная система:** Windows 8.1 64 - разрядная
- **IDEA:** IntelliJ IDEA 2022.2.1 (Community Edition) Build #IC-222.3739.54, built on August 16, 2022
- **Java:** corretto-11.0.16.1

**Comment by NataliKontakt** [comment]
## Код исправлен
https://github.com/alex311271/Team_diplom/blob/288606886616a0a98d5e841c24e5664f67a53bae/src/main/java/ru/netology/GameStore.java#L33-L40

## Тест проходит
![-1](https://user-images.githubusercontent.com/111893380/201474800-8e97b208-ac78-4887-8564-d98d4fdafc7e.png)
