### ISSUE TITLE
Метод getSumPlayedTime всегда возвращает 0

### ISSUE THREAD

**Issue by alex311271** [alex311271/Team_diplom#2]
### Описание.
Метод getSumPlayedTime всегда возвращает 0

### Локализация дефекта.
https://github.com/alex311271/Team_diplom/blob/cd681cab1e0e183541e927cf910010b6d02e6f92/src/main/java/ru/netology/GameStore.java#L76-L78

### Шаги воспроизведения.

1. Открыть ветку [gamestore](https://github.com/alex311271/Team_diplom.git) в IDEA
2. Запустить тест shouldGetSumPlayedTime в классе [GameStoreTest](https://github.com/alex311271/Team_diplom/blob/cd681cab1e0e183541e927cf910010b6d02e6f92/src/test/java/ru/netology/GameStoreTest.java)
3. Проверить результат в консоли.

**Ожидаемый результат:** тест проходит.
**Фактический результат:** тест не проходит. В консоли выводится сообщение: org.opentest4j.AssertionFailedError: Expected :17  
   Actual   :0
### Скриншот.

![shouldGetSumPlayedTime](https://user-images.githubusercontent.com/108461415/199983130-5651b66b-58dc-40e7-864d-1c9ce5236d6f.png)

### Окружение.

- Операционная система: Windows 8.1 64 - разрядная
- IDEA: IntelliJ IDEA 2022.2.1 (Community Edition) Build #IC-222.3739.54, built on August 16, 2022
- Java: corretto-11.0.16.1

**Comment by NataliKontakt** [comment]
## Код исправлен
https://github.com/alex311271/Team_diplom/blob/288606886616a0a98d5e841c24e5664f67a53bae/src/main/java/ru/netology/GameStore.java#L78-L85

## Тест проходит
![-2](https://user-images.githubusercontent.com/111893380/201474524-850fc48e-b5a3-4aec-a468-e12b371dcd81.png)
