### ISSUE TITLE
Метод sumGenre всегда возвращает 0

### ISSUE THREAD

**Issue by NataliKontakt** [alex311271/Team_diplom#3]
# Описание
Сумма времени игры равна 0.

# Локализация дефекта
https://github.com/alex311271/Team_diplom/blob/9edd425c2b17c915cd9b8994665a2f4b48dfb86c/src/main/java/ru/netology/Player.java#L46-L55

# Шаги воспроизведения

1. Открыть ветку [player] в IDEA
2. Запустить тест TestSum2Genre в классе [PlayerTest]
3. Проверить результат в консоли

*Ожидаемый результат:*  тест проходит.
*Фактический результат:*  тест не проходит. В консоли выводится сообщение: org.opentest4j.AssertionFailedError: 
Expected :8
Actual   :0

![TestSum2Genre](https://user-images.githubusercontent.com/111893380/201684567-7d9cc1b3-89fd-43e1-88b4-4b352957a2ec.png)

# Окружение
* **Операционная система:** Windows 10 64 - разрядная
*  **IDEA:** IntelliJ IDEA 2022.2.1 (Community Edition) Build #IC-222.3739.54, built on August 16, 2022
*  **Java:** OpenJDK 11

**Comment by alex311271** [comment]
Внесены изменения в метод sumGenre
 public int sumGenre(String genre) {
        int sum = 0;
        for (Game game : playedTime.keySet()) {
            if (game.getGenre().equals(genre)) {
                sum += playedTime.get(game);
            } else {
                sum = 0;
            }
        }
        return sum;
    }
