### ISSUE TITLE
Метод mostPlayerByGenre всегда возвращает null

### ISSUE THREAD

**Issue by NataliKontakt** [alex311271/Team_diplom#4]
# Описание
Метод mostPlayerByGenre всегда возвращает null

# Локализация дефекта
https://github.com/alex311271/Team_diplom/blob/9edd425c2b17c915cd9b8994665a2f4b48dfb86c/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения

1. Открыть ветку [player] в IDEA
2. Запустить тест MostPlayerGenre в классе [PlayerTest]
3. Проверить результат в консоли

*Ожидаемый результат:*  тест проходит.
*Фактический результат:*  тест не проходит. В консоли выводится сообщение: org.opentest4j.AssertionFailedError: 
Expected :ru.netology.Game@9683f5f
Actual   :null

![Метод mostPlayerByGenre возвращает null (1)](https://user-images.githubusercontent.com/111893380/201365001-baae8973-8b0f-46c8-b81c-7bf824253f66.png)

# Окружение
* **Операционная система:** Windows 10 64 - разрядная
*  **IDEA:** IntelliJ IDEA 2022.2.1 (Community Edition) Build #IC-222.3739.54, built on August 16, 2022
*  **Java:** OpenJDK 11

**Comment by alex311271** [comment]
Внесены изменения в метод mostPlayerByGenre
 public Game mostPlayerByGenre(String genre) {
        int maxTime = 0;
        Game maxGame = null;
        for (Game game : playedTime.keySet()) {
            if (game.getGenre().equals(genre)){
                int playerTime = playedTime.get(game);
                if (playerTime > maxTime) {
                    maxTime = playerTime;
                    maxGame = game;
                }
            }
        }

        return maxGame;
    }
